packages:
  - "apps/*"
  - "packages/*"

catalog:
  # TYPES
  typescript: 5.7.3
  "@types/node": ^20.10.5

  # ESLINT + PRETTIER
  eslint: ^9.0.0
  prettier: ^3.0.0
  # ⇑ PLUGINS
  eslint-config-prettier: ^9
  eslint-plugin-prettier: ^5

  # ENVIRONMENT
  dotenv: ^16.4.7

  # DEV
  nodemon: ^3.1.9
  ts-node: ^10.9.2
  tsc-alias: ^1.8.10
  tsconfig-paths: ^4.2.0

  # DATABASE
  mongoose: ^8.9.5